[package]
name = "rust-photo-frame"
version = "0.1.0"
edition = "2024"
description = "Raspberry Pi photo frame slideshow: scan dirs, circular buffer, fullscreen display."
license = "MIT"
repository = "https://github.com/vincentl/rust-photo-frame.git"
readme = "README.md"
keywords = ["slideshow", "photo", "frame", "wgpu", "winit", "raspberry-pi"]
categories = ["multimedia::images", "graphics", "command-line-utilities"]

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
