[workspace]
members = [
    "crates/photo-frame",
    "crates/buttond",
    "crates/wifi-manager",
]
resolver = "2"

[workspace.package]
edition = "2024"

[workspace.metadata]
# Workspace-level metadata placeholder for future shared settings.
