# Example configuration for rust-photo-frame
# Adjust values to match your hardware, library layout, and visual preferences.

# Root directory for images. Keep media in the managed subdirectories to
# separate synced libraries from ad-hoc drops:
#   cloud/ — populated by rclone or other sync jobs; safe to wipe/reseed.
#   local/ — manual imports (USB, scp) that should persist across syncs.
photo-library-path: /var/lib/photo-frame/photos

# Render/transition settings
transition:
  # List one or more transition kinds to rotate between.
  types: [fade, wipe, push, e-ink]
  # Choose how to iterate through the transition types: random or sequential.
  type-selection: random
  options:
    fade:
      duration-ms: 450
      through-black: false
    wipe:
      duration-ms: 600
      angle-list-degrees: [45.0, 225.0]
      angle-selection: sequential
      angle-jitter-degrees: 12.0
      softness: 0.08
    push:
      duration-ms: 520
      angle-list-degrees: [0.0, 180.0]
      angle-selection: random
      angle-jitter-degrees: 8.0
    e-ink:
      duration-ms: 1600
      flash-count: 0
      reveal-portion: 0.55
      stripe-count: 24
      flash-color: [0, 0, 0]

# Dwell time (ms) the current image remains fully displayed before the next transition
dwell-ms: 2000

# GPU render oversample factor (1.0 = native to screen)
oversample: 1.0

# Greeting screen displayed while the first images are prepared
greeting-screen:
  message: "Warming up your photo memories…"
  font: "Macondo"
  stroke-width: 16
  duration-seconds: 4
  colors:
    background: "#f8fafc"
    font: "#111827"
    accent: "#38bdf8"

# Sleep screen displayed when the frame is entering sleep mode
sleep-screen:
  message: "Going to Sleep"
  font: "Macondo"
  stroke-width: 16
  colors:
    background: "#111827"
    font: "#f8fafc"
    accent: "#38bdf8"

# Number of images to preload in the viewer (aligns with channel capacity)
viewer-preload-count: 3

# Concurrent image decodes in loader
loader-max-concurrent-decodes: 4

# Optional deterministic seed for the initial shuffle (set to null for random)
startup-shuffle-seed: null

photo-effect:
  # List zero or more effect types; set to [] to disable the stage entirely.
  types: []
  # Choose how to iterate through effects when multiple are configured.
  type-selection: random
  options:
    print-simulation:
      light-angle-degrees: 135.0
      relief-strength: 0.35
      ink-spread: 0.18
      sheen-strength: 0.22
      paper-color: [245, 244, 240]
      debug: false # Set true to only treat the left half for side-by-side comparison

playlist:
  new-multiplicity: 3
  half-life: 3 days

# Matting settings
matting:
  types: [fixed-color, blur, studio, fixed-image]
  # Choose how to iterate through the matting types: random or sequential.
  type-selection: random
  options:
    fixed-color:
      colors:
        - [0, 0, 0]
        - [32, 32, 32]
      color-selection: sequential # or random
      minimum-mat-percentage: 0.0
      max-upscale-factor: 1.0
    blur:
      minimum-mat-percentage: 3.5
      sigma: 32.0
      sample-scale: 0.125 # raise toward 1.0 for sharper mats at higher cost
      backend: neon # options: cpu, neon (auto-falls back to cpu if unsupported)
    studio:
      colors:
        - [24, 24, 24]
        - photo-average
        - [210, 210, 210]
      color-selection: random # or sequential
      minimum-mat-percentage: 8.0
      bevel-width-px: 4.0
      bevel-color: [255, 255, 255]
      texture-strength: 1.0 # 0.0 for smooth paper, 1.0 default weave
      warp-period-px: 5.6 # spacing between vertical warp threads in px
      weft-period-px: 5.2 # spacing between horizontal weft threads in px
    fixed-image:
      minimum-mat-percentage: 6.0
      path:
        [
          /opt/photo-frame/share/backgrounds/blue-textured-brick-wall-background.jpg,
        ]
      path-selection: sequential # or random
      fit: cover # options: cover, contain, stretch
