photo-library-path: /Users/vincent/rust-photo-frame/photo-library-test

# Render/transition settings
# Cross-fade duration in milliseconds
fade-ms: 400
# Dwell time (ms) the current image remains fully displayed before fading
dwell-ms: 2000
# Number of images to preload in the viewer (aligns with channel capacity)
viewer-preload-count: 3
# GPU decode/render oversample factor (1.0 = native to screen)
oversample: 1.0
# Concurrent image decodes in loader
loader-max-concurrent-decodes: 4

playlist:
  new-multiplicity: 3
  half-life: 3 days

# Matting settings
matting:
  type: fixed-color
  color: [0, 0, 0]
  minimum-mat-percentage: 0.0
  max-upscale-factor: 1.0
# To enable the blur mat optimized for Raspberry Pi, switch to:
# matting:
#   type: blur
#   sigma: 20.0
#   max-sample-dim: 1536
#   backend: neon        # options: cpu, neon (defaults to cpu)
# Example studio mat with a crisp white bevel:
# matting:
#   type: studio
#   minimum-mat-percentage: 3.5
#   bevel-width-px: 4.0
#   bevel-color: [255, 255, 255]
#   texture-strength: 1.0
#   warp-period-px: 22.0
#   weft-period-px: 22.0
# Example fixed background image scaled to cover the screen:
# matting:
#   type: fixed-image
#   path: /path/to/background.png
#   fit: cover             # options: cover, contain, stretch
