photo-library-path: /Users/vincent/rust-photo-frame/photo-library-test

# Render/transition settings
# Transition behavior between photos
transition:
  type: random
  options:
    fade:
      duration-ms: 400
    wipe:
      duration-ms: 550
      angle-list-degrees: [45.0, 225.0]
      angle-selection: round-robin
      angle-jitter-degrees: 5.0
      softness: 0.08
    push:
      duration-ms: 520
      angle-list-degrees: [0.0, 180.0]
# Dwell time (ms) the current image remains fully displayed before the next transition
dwell-ms: 2000
# Number of images to preload in the viewer (aligns with channel capacity)
viewer-preload-count: 3
# GPU decode/render oversample factor (1.0 = native to screen)
oversample: 1.0
# Concurrent image decodes in loader
loader-max-concurrent-decodes: 4
# Optional deterministic seed for the initial shuffle (set to null for random)
startup-shuffle-seed: null

playlist:
  new-multiplicity: 3
  half-life: 3 days

# Matting settings
matting:
  type: random
  options:
    fixed-color:
      color: [0, 0, 0]
      minimum-mat-percentage: 0.0
      max-upscale-factor: 1.0
    blur:
      minimum-mat-percentage: 3.5
      sigma: 20.0
      max-sample-dim: 1536
      backend: neon # options: cpu, neon (defaults to cpu)
    studio:
      minimum-mat-percentage: 8.0
      bevel-width-px: 4.0
      bevel-color: [255, 255, 255]
      texture-strength: 1.0 # 0.0 for smooth paper, 1.0 default weave
      warp-period-px: 5.6 # spacing between vertical warp threads in px
      weft-period-px: 5.2 # spacing between horizontal weft threads in px
    fixed-image:
      path: /path/to/background.png
      fit: cover # options: cover, contain, stretch
