# Example configuration for rust-photo-frame
# Adjust values to match your hardware, library layout, and visual preferences.

# Root directory for images. Keep media in the managed subdirectories to
# separate synced libraries from ad-hoc drops:
#   cloud/ — populated by rclone or other sync jobs; safe to wipe/reseed.
#   local/ — manual imports (USB, scp) that should persist across syncs.
photo-library-path: /var/lib/photo-frame/photos

# Unix domain socket path for runtime control commands
control-socket-path: /run/photo-frame/control.sock

# Render/transition settings
transition:
  # Choose how the viewer advances through the entries below: fixed, random, or sequential.
  selection: random
  # Declare one or more transition entries. Repeat a kind to weight it more heavily.
  active:
    - kind: fade
      duration-ms: 450
      through-black: false
    - kind: wipe
      duration-ms: 600
      angle-list-degrees: [45.0, 225.0]
      angle-selection: sequential
      angle-jitter-degrees: 12.0
      softness: 0.08
    - kind: push
      duration-ms: 520
      angle-list-degrees: [0.0, 180.0]
      angle-selection: random
      angle-jitter-degrees: 8.0
    - kind: e-ink
      duration-ms: 1600
      flash-count: 0
      reveal-portion: 0.55
      stripe-count: 24
      flash-color: [0, 0, 0]
    - kind: iris
      duration-ms: 900
      blades: 7
      rotate-radians: 1.05
      direction: open
      fill-rgba: [0.85, 0.85, 0.85, 1.0]
      stroke-rgba: [0.10, 0.10, 0.10, 1.0]
      stroke-width: 1.5
      tolerance: 0.25

# Dwell time (ms) the current image remains fully displayed before the next transition
dwell-ms: 2000

# GPU render oversample factor (1.0 = native to screen)
oversample: 1.0

# Greeting screen displayed while the first images are prepared
greeting-screen:
  message: "Warming up your photo memories…"
  font: "Macondo"
  stroke-width: 16
  duration-seconds: 16
  colors:
    background: "#f0e8d5"   # warm parchment
    font: "#2d3748"         # soft charcoal
    accent: "#7da8a5"       # tranquil sea-glass teal

# Sleep screen displayed when the frame is entering sleep mode
sleep-screen:
  message: "Tucking in for a nap…"
  font: "Macondo"
  stroke-width: 16
  colors:
    background: "#1e293b"   # deep slate blue
    font: "#f0e8d5"         # warm ivory
    accent: "#375978"       # muted indigo-teal

# Optional awake schedule (viewer sleeps outside these intervals)
awake-schedule:
  timezone: "America/New_York"
  awake-scheduled:
    daily:
      - ["07:15", "22:00"]
    weekdays:
      - ["06:45", "23:00"]
    weekend:
      - ["07:15", "12:00"]
      - ["15:00", "23:30"]
    friday: []
    saturday:
      - ["08:00", "12:00"]
      - ["16:00", "23:00"]

# Number of images to preload in the viewer (aligns with channel capacity)
viewer-preload-count: 3

# Concurrent image decodes in loader
loader-max-concurrent-decodes: 4

# Optional deterministic seed for the initial shuffle (set to null for random)
startup-shuffle-seed: null

photo-effect:
  # Choose how the viewer advances through the entries below when enabled.
  selection: random
  # Provide zero or more effect entries; leave empty to disable the stage.
  active: []
  # Example configuration:
  # active:
  #   - kind: print-simulation
  #     light-angle-degrees: 135.0
  #     relief-strength: 0.35
  #     ink-spread: 0.18
  #     sheen-strength: 0.22
  #     paper-color: [245, 244, 240]
  #     debug: false # Set true to only treat the left half for side-by-side comparison

playlist:
  new-multiplicity: 3
  half-life: 3 days

# Matting settings
matting:
  # Choose how the viewer advances through the mats below: fixed, random, or sequential.
  selection: random
  # Provide one or more mat definitions. Repeat a kind to weight or alternate variants.
  active:
    - kind: fixed-color
      colors:
        - [0, 0, 0]
        - [32, 32, 32]
      color-selection: sequential # or random
      minimum-mat-percentage: 0.0
      max-upscale-factor: 1.0
    - kind: blur
      minimum-mat-percentage: 3.5
      sigma: 32.0
      sample-scale: 0.125 # raise toward 1.0 for sharper mats at higher cost
      backend: neon # options: cpu, neon (auto-falls back to cpu if unsupported)
    - kind: studio
      colors:
        - [24, 24, 24]
        - photo-average
        - [210, 210, 210]
      color-selection: random # or sequential
      minimum-mat-percentage: 8.0
      bevel-width-px: 4.0
      bevel-color: [255, 255, 255]
      texture-strength: 1.0 # 0.0 for smooth paper, 1.0 default weave
      warp-period-px: 5.6 # spacing between vertical warp threads in px
      weft-period-px: 5.2 # spacing between horizontal weft threads in px
    - kind: fixed-image
      minimum-mat-percentage: 6.0
      path:
        [
          /opt/photo-frame/share/backgrounds/blue-textured-brick-wall-background.jpg,
        ]
      path-selection: sequential # or random
      fit: cover # options: cover, contain, stretch
