# Example configuration for rust-photo-frame
# Copy as config.yaml and adjust paths/settings as needed.

# Root directory for images (scanned recursively)
photo-library-path: /absolute/path/to/your/photo/library

# Render/transition settings
# Transition configuration (select fade, wipe, push, or random)
transition:
  type: random
  duration-ms: 400
  fade:
    through-black: false
  wipe:
    angle-deg: 0.0
    softness-px: 32.0
    reverse: false
  push:
    direction: left
  random:
    fade-weight: 1.0
    wipe-weight: 1.0
    push-weight: 1.0
# Dwell time (ms) the current image remains fully displayed before transitioning
dwell-ms: 2000

# Viewer buffering and pipeline backpressure
# Number of images the viewer preloads; also sets viewer channel capacity
viewer-preload-count: 3
# Maximum number of concurrent image decodes in the loader
loader-max-concurrent-decodes: 4

# GPU render oversample factor (1.0 = native to screen)
oversample: 1.0
