# Example configuration for rust-photo-frame
# Copy as config.yaml and adjust paths/settings as needed.

# Root directory for images (scanned recursively)
photo-library-path: /absolute/path/to/your/photo/library

# Render/transition settings
# Cross-fade duration in milliseconds
fade-ms: 400
# Dwell time (ms) the current image remains fully displayed before fading
dwell-ms: 2000

# Viewer buffering and pipeline backpressure
# Number of images the viewer preloads; also sets viewer channel capacity
viewer-preload-count: 3
# Maximum number of concurrent image decodes in the loader
loader-max-concurrent-decodes: 4

# GPU render oversample factor (1.0 = native to screen)
oversample: 1.0

# First-run Wi-Fi setup portal (used on Raspberry Pi)
wifi-setup:
  enabled: true
  wifi-interface: wlan0
  hotspot-ssid: Frame Setup
  hotspot-password: framesetup
  hotspot-start-command:
    - sudo
    - systemctl
    - start
    - frame-hotspot.service
  hotspot-stop-command:
    - sudo
    - systemctl
    - stop
    - frame-hotspot.service
  portal-bind-address: 0.0.0.0
  portal-port: 8080
  portal-hostname: 10.0.0.1
  wpa-supplicant-path: /etc/wpa_supplicant/wpa_supplicant.conf
  connection-check-timeout-secs: 45
  connection-check-interval-secs: 3
  restart-command: []
