# Example configuration for rust-photo-frame
# Copy as config.yaml and adjust paths/settings as needed.

# Root directory for images (scanned recursively)
photo-library-path: /absolute/path/to/your/photo/library

# Render/transition settings
# Configure the transition between photos
transition:
  type: fade
  duration-ms: 400
  # Example: enable the e-ink slow refresh effect.
  # type: fixed
  # options:
  #   e-ink:
  #     duration-ms: 1600
  #     flash-count: 3
  #     reveal-portion: 0.55
  #     stripe-count: 24
# Dwell time (ms) the current image remains fully displayed before the next transition
dwell-ms: 2000

# Viewer buffering and pipeline backpressure
# Number of images the viewer preloads; also sets viewer channel capacity
viewer-preload-count: 3
# Maximum number of concurrent image decodes in the loader
loader-max-concurrent-decodes: 4

# GPU render oversample factor (1.0 = native to screen)
oversample: 1.0
